"use client"

import { createContext, useContext, useState, type ReactNode, useEffect } from "react"

type Language = "ar" | "fr" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  dir: "ltr" | "rtl"
  t: (key: string) => string
}

const translations = {
  ar: {
    "nav.home": "الرئيسية",
    "nav.programs": "البرامج",
    "nav.certifications": "الشهادات",
    "nav.about": "عنا",
    "nav.contact": "اتصل بنا",
    "nav.elearning": "التعلم الإلكتروني",

    "hero.title": "معهد التدريب المهني",
    "hero.subtitle": "نفتح لك أبواب المستقبل من خلال تعليم اللغات والتمريض المعتمد دولياً",
    "hero.cta": "ابدأ رحلتك معنا",
    "hero.location": "فاس، المغرب",
    "hero.certified": "معتمد ومعترف به رسمياً",
    "hero.graduates": "خريجون سعداء",
    "hero.experience": "سنوات من الخبرة",
    "hero.successRate": "نسبة النجاح",

    "programs.title": "برامجنا التعليمية",
    "programs.languages": "برنامج اللغات",
    "programs.languages.desc": "تعلم اللغات الأجنبية من خلال منهج معترف به دولياً",
    "programs.nursing": "برنامج التمريض",
    "programs.nursing.desc": "تدريب تمريض متقدم معتمد وآمن مع معايير عالمية",
    "programs.english": "اللغة الإنجليزية",
    "programs.french": "اللغة الفرنسية",
    "programs.spanish": "اللغة الإسبانية",
    "programs.clinical": "التدريب العملي",
    "programs.standards": "المعايير الدولية",
    "programs.certification": "الشهادة الجاهزة",
    "programs.learn": "تعرف على المزيد",
    "programs.why": "لماذا اختيار IPFPSP-FES؟",
    "programs.experts": "معلمون خبراء",
    "programs.smallClasses": "فصول صغيرة",
    "programs.modern": "منهج حديث",
    "programs.certified": "برامج معتمدة",
    "programs.excellence": "التميز في التعليم مع معايير دولية وطرق تدريس حديثة",

    "certs.title": "معترف به دولياً",
    "certs.international": "شهادات معترف بها دولياً",
    "certs.standards": "معايير تعليمية عالمية",
    "certs.opportunities": "فرص توظيف عالمية",
    "certs.recognized": "معترف به من قبل هيئات التعليم الدولية وأصحاب العمل في جميع أنحاء العالم",
    "certs.curriculum": "المناهج الدراسية متوافقة مع معايير الاتحاد الأوروبي والمعايير الدولية",
    "certs.graduates": "يجد الخريجون فرص عمل في جميع أنحاء أوروبا والشرق الأوسط",
    "certs.subtitle": "شهاداتنا والاعتماديات الخاصة بنا تضمن جودة التعليم والاعتراف العالمي",
    "certs.accredited": "معتمد من قبل",

    "enroll.title": "التحق بنا اليوم",
    "enroll.desc": "انضم إلى مئات الطلاب السعداء الذين بدأوا رحلتهم معنا ونجحوا في تحقيق أحلامهم",
    "enroll.button": "اطلب الالتحاق",
    "enroll.contact": "أو اتصل بنا",
    "enroll.phone": "+212 6 30 99 50 44",
    "enroll.email": "ipfpsp@gmail.com",
    "enroll.getInTouch": "تواصل معنا",
    "enroll.questions": "هل لديك أسئلة حول برامجنا؟ لا تتردد! فريق القبول لدينا هنا لمساعدتك في كل خطوة من رحلتك التعليمية.",
    "enroll.phone.label": "الهاتف",
    "enroll.email.label": "البريد الإلكتروني",
    "enroll.location": "الموقع",
    "enroll.support": "الدعم المتاح 24/7",
    "enroll.response": "وقت الاستجابة 1-2 ساعات",
    "enroll.fullName": "الاسم الكامل",
    "enroll.fullName.placeholder": "اسمك الكامل",
    "enroll.email.placeholder": "بريدك@email.com",
    "enroll.phone.placeholder": "+212 ...",
    "enroll.program": "البرنامج المهتم به",
    "enroll.program.select": "اختر برنامج",
    "enroll.program.languages": "برنامج اللغات",
    "enroll.program.nursing": "برنامج التمريض",
    "enroll.program.both": "كلا البرنامجين",
    "enroll.message": "الرسالة",
    "enroll.message.placeholder": "أخبرنا عن نفسك...",
    "enroll.submit": "إرسال",
    "enroll.thanks": "شكراً لك!",
    "enroll.thanks.message": "تم استقبال استفسارك وسنتصل بك قريباً.",
    "enroll.contact.within": "سنتصل بك خلال 24 ساعة",

    "footer.about": "عن المعهد",
    "footer.programs": "البرامج",
    "footer.contact": "اتصل بنا",
    "footer.rights": "جميع الحقوق محفوظة © 2025",
    "footer.description": "معهد تعليمي رائد لتدريس اللغات والتمريض في فاس، المغرب. معتمد للفرص الدولية.",
    "footer.mission": "رسالتنا",
    "footer.team": "فريقنا",
    "footer.stories": "قصص النجاح",
    "footer.blog": "المدونة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.cookies": "ملفات تعريف الارتباط",
    "footer.location": "فاس، المغرب",

    institution_name: "معهد التدريب المهني الخاص للصحة والعمل المساعد",
    authorization_date: "المؤسسة معتمدة من قبل الدولة تحت رقم 5/0 / 2025",

    program1_name: "ممرض متعدد التخصصات",
    program1_level: "مستوى بكالوريوس - جميع التخصصات",
    program1_duration: "مدة التدريب",
    program1_requirement: "المستوى التعليمي المطلوب",
    program1_years: "3 سنوات",

    program2_name: "مساعد صحي",
    program2_level: "مستوى الصف الثالث الإعدادي",
    program2_duration: "مدة التدريب",
    program2_requirement: "المستوى التعليمي المطلوب",
    program2_years: "سنة واحدة",

    education_level: "المستوى التعليمي",
    admission_requirement: "متطلبات القبول",
    training_duration: "مدة التدريب",
    enroll_now: "التحق الآن",
    contact_us: "اتصل بنا",
    follow_us: "تابعنا",
    officially_authorized: "معتمد رسمياً من قبل وزارة التعليم المغربية",

    "contact.workingHours": "ساعات العمل",
    "contact.weekdays": "الإثنين - الجمعة: 8:00 - 18:00",
    "contact.saturday": "السبت: 10:00 - 14:00",
    "contact.emergency": "حالات طارئة:",
    "contact.germanLessons": "دروس اللغة الألمانية",
    "contact.nursingCourses": "برامج التمريض",
    "contact.jobsGermany": "الأسئلة حول الوظائف والتدريب في ألمانيا",
    "contact.germanNumber": "+49 174 77 80 532",
    "contact.nursingNumber": "+212 7 79 74 75 29",
    "contact.germanJobsNumber": "+212 34 43 61 00",
    "contact.germanLessonsNumber": "+212 6 30 99 50 44",
    "contact.important": "في الحالات المهمة والاستفسارات",
    "contact.address": "إقامة مكاتب رياض سلام رقم 3، تجزئة مولان الإدريسية، شارع القوات المسلحة الملكية، فاس، المغرب",
    "contact.phone": "+212 5 35 94 34 68",
    "contact.whatsapp": "+49 174 7780532",
    "contact.email": "info@ipfpsp.ma",

    "about.title": "من نحن",
    "about.description": "مرحباً بك في معهد IPFPSP! نحن مؤسسة تعليمية خاصة متخصصة في تكوين المهنيين في مجالي الصحة والتمريض، تقع في قلب مدينة فاس التاريخية. حصلنا على الترخيص الرسمي من الدولة (رقم 5/0/2025)، ونفتخر بتقديم برامج دراسية عالية الجودة تواكب المعايير الوطنية والدولية. هدفنا؟ إعداد جيل جديد من الكفاءات الصحية القادرة على تقديم رعاية متميزة وخدمة المجتمع بكل إخلاص.",
    "about.description2": "ما يميزنا في IPFPSP هو التكوين المتكامل الذي يجمع بين النظرية والتطبيق. طلابنا يحصلون على دروس نظرية من أساتذة خبراء، بالإضافة إلى تدريب عملي مكثف في مختبراتنا المتطورة، وفترات تدريب ميداني حقيقية في مستشفيات ومراكز صحية شريكة. هذا كله لضمان أن خريجينا جاهزون تماماً للعمل الفعلي. ونفتح أبوابنا للطلاب من كل مكان - من المغرب ومن خارجها - ونقدم دعماً خاصاً للطلبة الأجانب وبرامج تأهيلية إضافية للراغبين في العمل دولياً، خاصة في ألمانيا حيث الطلب الكبير على الكفاءات الصحية.",

    "vision.title": "رؤيتنا",
    "vision.description": "رؤيتنا بسيطة وواضحة: نريد أن نكون المرجع الأول في التكوين الصحي وشبه الطبي، ليس فقط في المغرب بل على المستوى الدولي أيضاً. نحلم بقطاع صحي أفضل، ونؤمن أن هذا يبدأ بتخريج مهنيين مؤهلين يجمعون بين العلم والمهارة والإنسانية. نريد بيئة تعليمية يشعر فيها كل طالب وطالبة بأنهم قادرون على تحقيق أحلامهم وتطوير مواهبهم ليصبحوا رواداً في مجالاتهم. ونعمل على بناء شراكات دولية وتبني أفضل الممارسات العالمية، حتى يكون خريجونا سفراء للتميز أينما ذهبوا. في النهاية، كل طالب عندنا هو استثمار في مستقبل أفضل للصحة والرعاية.",

    "values.title": "قيمنا",
    "values.excellence.title": "الجودة والتميز",
    "values.excellence.desc": "نحن ملتزمون بأعلى معايير الجودة في كل ما نقدمه. يشمل ذلك المحتوى التعليمي الحديث، وطرق التدريس الفعّالة، والتقييم المستمر لأدائنا. نسترشد بتوجيهات منظمة الصحة العالمية (WHO) ومعايير اليونسكو للتعليم التقني والمهني (UNESCO TVET) لضمان أن تكويننا يتوافق مع أفضل المعايير الدولية.",
    "values.professionalism.title": "الاحترافية والأخلاق",
    "values.professionalism.desc": "نعتبر أن أخلاقيات المهنة والمسؤولية المهنية لا تقل أهمية عن المهارات التقنية. نغرس في طلابنا قيم الأمانة والنزاهة واحترام سرية معلومات المرضى، بالإضافة إلى روح تحمل المسؤولية والعمل ضمن فريق. التزامنا بالاحترافية يظهر في طريقة إدارتنا للمعهد وفي إعداد طلابنا ليكونوا قدوة في أماكن عملهم المستقبلية.",
    "values.humanity.title": "الإنسانية والتعاطف",
    "values.humanity.desc": "مهنة الصحة هي أولاً وأخيرًا مهنة إنسانية. لذلك نعلم طلابنا أن حسن التعامل مع المرضى والرحمة بهم جزء لا يتجزأ من العمل الصحي. نركز على تنمية مهارات التواصل والتعاطف، ونشجع روح التعاون ومساعدة الآخرين، لكي يصبح خريجونا مهنيين بقلوب رحيمة يفهمون احتياجات المرضى النفسية والاجتماعية إلى جانب احتياجاتهم الطبية.",
    "values.innovation.title": "الابتكار والتطوير",
    "values.innovation.desc": "نشجع على اتباع أساليب تعليم حديثة وإبداعية. نوفر أحدث التجهيزات في مختبراتنا ونستخدم التقنيات الرقمية وطرق المحاكاة في التدريب. ثقافة البحث والتطوير حاضرة بقوة في معهدنا، حيث ندعم مبادرات الطلاب ومشاريعهم الابتكارية، ونسعى باستمرار لتحديث برامجنا لتتماشى مع التطورات العلمية والتكنولوجية في مجالات الصحة.",
    "values.openness.title": "الانفتاح والتعددية",
    "values.openness.desc": "نعزز بيئة تعليمية منفتحة على مختلف الثقافات والخلفيات. نفتخر بأن يضم معهدنا طلابًا متنوعين يجمعهم هدف واحد هو خدمة الصحة. كما نبني جسور تواصل مع مؤسسات تعليمية وصحية عبر العالم. هذا الانفتاح الدولي، إلى جانب التعددية الثقافية على مستوى طلابنا وأساتذتنا، يخلق تجربة تعليمية فريدة تُعدّ الطلاب للعمل في أي سياق محلي أو عالمي بثقة وكفاءة.",

    "campus.title": "الحرم الجامعي",
    "campus.description": "يقع معهد IPFPSP في مدينة فاس التاريخية، ويضم حرماً تعليمياً حديثاً ومتكاملاً مصممًا خصيصًا لتلبية احتياجات التكوين الصحي. يضم الحرم قاعات دراسية مجهزة بأحدث وسائل العرض والتكنولوجيا التعليمية، مما يتيح لأعضاء هيئة التدريس تقديم الدروس بشكل تفاعلي وجذاب. لدينا أيضًا مختبرات علمية ومرافق لمحاكاة الإجراءات الطبية، حيث يمكن للطلاب تطبيق ما يتعلمونه عمليًا واكتساب المهارات التقنية في بيئة آمنة وتحت إشراف مختصين.",
    "campus.description2": "تتوفر في المعهد مكتبة متخصصة تحتوي على مجموعة واسعة من المراجع في مجالات التمريض والصحة باللغات العربية والفرنسية والإنجليزية، مما يساعد الطلاب على إثراء معرفتهم والاطلاع على أحدث الأبحاث. كما يوفر الحرم فضاءات مريحة للدراسة الفردية والعمل الجماعي، إلى جانب مرافق ترفيهية واستراحات لراحة الطلاب بين الحصص. لقد حرصنا على أن يكون حرمنا بيئة محفزة على التعلم، وفي نفس الوقت مكانًا يشعر فيه الطالب بالانتماء والأمان.",
    "campus.facility1.title": "قاعات دراسية مجهزة",
    "campus.facility1.desc": "قاعات دراسية مجهزة بأحدث وسائل العرض والتكنولوجيا التعليمية",
    "campus.facility2.title": "مختبرات علمية",
    "campus.facility2.desc": "مختبرات علمية ومرافق لمحاكاة الإجراءات الطبية",
    "campus.facility3.title": "مكتبة متخصصة",
    "campus.facility3.desc": "مكتبة متخصصة تحتوي على مجموعة واسعة من المراجع",
    "campus.facility4.title": "مرافق رقمية",
    "campus.facility4.desc": "مرافق رقمية ومنصات تعليم إلكترونية",
    "campus.facility5.title": "فضاءات للدراسة",
    "campus.facility5.desc": "فضاءات مريحة للدراسة الفردية والعمل الجماعي",

    "programs.delegue.title": "مندوب طبي",
    "programs.delegue.desc": "يُعِدُّ برنامج مندوب طبي (Délégué Médical) المشاركين للعمل كمندوبين طبيين في قطاع الصناعات الدوائية. يتعلم المتدربون كيفية عرض المنتجات الطبية والأدوية بشكل مهني وتعزيز التواصل بين شركات الأدوية ومقدمي الرعاية الصحية.",
    "programs.pedagogique.title": "التكوين التربوي",
    "programs.pedagogique.desc": "يؤهل برنامج التكوين التربوي (Formation Pédagogique) المشاركين للقيام بمهام تربوية في رياض الأطفال والمدارس. يكتسب المتدربون أساسيات في علم نفس النمو وطرق التدريس ورعاية الأطفال للعمل باحترافية مع الأطفال في المجال التعليمي.",
    "programs.paramedical.title": "المهن شبه الطبية",
    "programs.paramedical.desc": "تزود دورة المهن شبه الطبية (Paramedical) المتدربين بالمعارف والمهارات الأساسية في مجال الرعاية الصحية. يتم إعداد المشاركين للقيام بمهام مساندة في القطاع الطبي والعمل ضمن فرق الرعاية الصحية.",
    "programs.koch.title": "تدريب الطهاة",
    "programs.koch.desc": "يُعِدُّ برنامج تدريب الطهاة (Koch) المشاركين لفنون الطهي وإدارة المطبخ. من خلال التدريب العملي، يتعلم المتدربون تقنيات الطهي الأساسية وتخطيط قوائم الطعام وقواعد النظافة، مما يؤهلهم للعمل بنجاح كطهاة في قطاع المطاعم والفنادق.",
    "programs.premiers_secours.title": "الإسعافات الأولية",
    "programs.premiers_secours.desc": "تشمل جلسات تعليم الإسعافات الأولية (Séances instructives de premiers secours) تدريبًا عمليًا على المهارات الأساسية لإنقاذ الحياة. يتعلم المشاركون كيفية التصرف بشكل صحيح في حالات الطوارئ وتقديم الإسعافات الضرورية للمصابين إلى حين وصول فرق الإسعاف المتخصصة.",
    "programs.bureautique.title": "المعلوماتية المكتبية",
    "programs.bureautique.desc": "تزود دورة المعلوماتية المكتبية (Bureautique) المشاركين بالمهارات الأساسية لاستخدام برامج المكتب وتنظيم الأعمال الإدارية. يتعلم المتدربون استخدام البرامج الشائعة مثل حزمة Microsoft Office (Word وExcel وPowerPoint وOutlook) بكفاءة، ويكتسبون مهارات تنظيمية تمكنهم من أداء المهام المكتبية بفعالية.",
    "programs.physiotherapie.title": "أخصائي العلاج الطبيعي",
    "programs.physiotherapie.desc": "يتضمن البرنامج دراسة نظريات العلاج الطبيعي وتقنيات إعادة التأهيل البدني. يتعلم الطالب طرق تقييم وعلاج اضطرابات الجهاز الحركي، بما في ذلك التمارين العلاجية، والتدليك الطبي، وتقنيات استخدام المعدات الفيزيائية.",
    "programs.laboratoire.title": "تقني مختبر التحاليل الطبية",
    "programs.laboratoire.desc": "يُعنى هذا البرنامج بتكوين تقنيين متخصصين في إجراء التحاليل المخبرية الطبية. يدرس الطلاب مواد في علم الأحياء الدقيقة والكيمياء الحيوية وعلوم المختبر، ويتدربون على التعامل مع العينات البيولوجية وتشغيل أجهزة التحليل الحديثة.",
    "programs.secretaire.title": "كاتب(ة) طبي(ة)",
    "programs.secretaire.desc": "يُركز هذا البرنامج على الجانب الإداري والتنظيمي في المؤسسات الصحية. يتعلم الطلاب المصطلحات الطبية باللغات المختلفة، وإدارة ملفات المرضى، والتنظيم الإداري للوحدات الصحية.",

    "diplomas.title": "الشهادات (الدبلومات)",
    "diplomas.description": "يحصل الطالب بعد إنهاء أي من برامج التكوين بنجاح على شهادة دبلوم معتمدة رسميًا من الدولة المغربية. تُعد هذه الشهادة دليلًا على أن حاملها قد تلقى تكوينًا محترفًا يستوفي معايير الجودة الوطنية. إن اعتمادنا من طرف الدولة (ترخيص رقم 5/0/2025) يعني أن شهادات IPFPSP تحظى بالاعتراف من قبل وزارة التربية الوطنية، مما يتيح للخريجين فرصًا واسعة للعمل في القطاعين العام والخاص داخل المغرب.",
    "diplomas.description2": "ولا يقتصر تميز شهاداتنا على الاعتراف المحلي فقط، بل نسعى جاهدين لجعلها متوافقة مع المعايير الدولية. لقد صُمِّمت مناهجنا وفق مبادئ المنظمات الدولية الرائدة: نعتمد إرشادات منظمة الصحة العالمية فيما يتعلق بتدريب العاملين في المجال الصحي، ونلتزم بتوجيهات منظمة اليونسكو للتعليم التقني والمهني (TVET) لضمان أن محتوى التكوين يواكب التطورات العالمية ويلبي احتياجات سوق العمل الحديث.",

    "languages.title": "دورات اللغة",
    "languages.description": "في إطار تحضير طلابنا لمسار مهني ناجح سواء داخل المغرب أو خارجه، نوفر في IPFPSP دورات لتعليم اللغات تكميلية إلى جانب البرامج التخصصية. نؤمن بأن امتلاك مهارات لغوية إضافية بات ضرورة في قطاع الصحة الذي أصبح عالميًا ومترابطًا.",
    "languages.german.title": "دورة اللغة الألمانية",
    "languages.german.desc": "نقدم دروسًا في اللغة الألمانية مصممة خصيصًا للعاملين في المجال الصحي. نساعد الطلاب على بلوغ مستوى B2 حسب الإطار الأوروبي المرجعي الموحد للغات (CEFR)، والذي يُعد مستوى متقدمًا يتيح التواصل الفعّال في بيئة عمل ألمانية. تشمل الدورة مفردات طبية أساسية ومصطلحات تقنية تحتاجها الكوادر الصحية.",
    "languages.german.levels": "نقدم دورات اللغة الألمانية لجميع المستويات من A1 إلى C1، بالإضافة إلى دورات تحضيرية خاصة للإعداد للامتحانات المعتمدة مثل Telc وÖSD وامتحانات معهد غوته، وذلك لضمان جاهزية المتدربين للحصول على شهادات معترف بها.",
    "languages.english.title": "دورة اللغة الإنجليزية",
    "languages.english.desc": "اللغة الإنجليزية هي لغة العلوم والتواصل الدولي. من خلال دورات الإنجليزية المتوفرة لدينا، نُمكّن طلابنا من تحسين مهاراتهم في القراءة (لفهم المقالات والبحوث الطبية العالمية) والكتابة (للتواصل عبر البريد الإلكتروني وإعداد التقارير) والمحادثة (للتفاعل مع مرضى أو زملاء من جنسيات مختلفة).",
    "languages.english.levels": "نقدم دورات اللغة الإنجليزية لجميع المستويات من A1 إلى C1. كما نوفر دورات تحضيرية للإعداد لامتحانات اللغة الإنجليزية الدولية مثل TOEFL وIELTS، مما يساعد المتدربين على اجتياز هذه الاختبارات بنجاح والحصول على شهادات معترف بها.",
    "languages.french.title": "دورة اللغة الفرنسية",
    "languages.french.desc": "نظرًا لأن اللغة الفرنسية هي لغة التدريس الأساسية في معظم المواد الطبية بالمغرب، فإننا نعرض دورات في الفرنسية للطلاب غير الناطقين بها أو للراغبين في تعزيز مستواهم. تهدف هذه الدورات إلى تطوير مهارات الطلاب في فهم المصطلحات الطبية بالفرنسية والتواصل بثقة في البيئات المهنية الفرنكوفونية.",
    "languages.french.levels": "نقدم دورات اللغة الفرنسية لجميع المستويات من A1 إلى C1. وعند الحاجة، نوفر أيضًا دورات تحضيرية للإعداد للامتحانات الرسمية في اللغة الفرنسية مثل DELF/DALF، وذلك لمساعدة المتدربين على الحصول على شهادات معترف بها في اللغة الفرنسية.",

    "online.title": "التعلم عبر الإنترنت",
    "online.description": "تجاوبًا مع التطورات التقنية الحديثة وحاجة بعض الطلاب إلى المرونة في التعلم، تبنى معهد IPFPSP نظام التعلم عن بُعد (الإلكتروني) كجزء مكمل لبرامجه. وفرنا منصة إلكترونية تعليمية تتيح للطالب الدخول إلى موارد رقمية متنوعة: محاضرات مسجلة، عروض تقديمية، كتب إلكترونية، وبنوك أسئلة للتدريب على الاختبارات.",
    "online.description2": "يعتمد نظام التعلم المدمج لدينا على الدمج بين التعليم الحضوري والافتراضي. على سبيل المثال، قد يحضر الطالب المحاضرات العملية والتدريبات المخبرية في المعهد وجهاً لوجه، بينما يتابع الدروس النظرية الأقل تفاعلاً عبر الإنترنت في الوقت المناسب له.",
    "online.allCourses": "نقدم جميع دوراتنا أيضًا عبر الإنترنت، مما يتيح لك التعلم بمرونة من المنزل أو أي مكان آخر. نوفر منصات تعليم إلكترونية حديثة ومواد رقمية لضمان تجربة تعلم تفاعلية وفعّالة لجميع المتدربين.",

    "companies.title": "عروض للشركات",
    "companies.description": "إيمانًا منا بأن تطوير القطاع الصحي مسؤولية مشتركة، يحرص معهد IPFPSP على تقديم خدمات وعروض موجهة للشركات والمؤسسات العاملة في ميدان الصحة داخل المغرب وخارجه.",
    "companies.training.title": "تدريب مخصص للموظفين",
    "companies.training.desc": "يمكننا تصميم وتنفيذ دورات تدريبية خاصة لموظفي المؤسسات الصحية حسب احتياجاتهم. على سبيل المثال، نوفر دورات الإسعافات الأولية والسلامة الصحية لموظفي الشركات غير الطبية الراغبين في تأهيل كوادرها في هذا المجال.",
    "companies.partnerships.title": "شراكات في مجال التدريب التطبيقي",
    "companies.partnerships.desc": "ندعو المستشفيات والعيادات والمختبرات للمشاركة معنا في اتفاقيات شراكة لاستقبال طلبتنا في فترات التدريب الميداني. من خلال هذه الشراكات، تحصل المؤسسات على فرصة التعرف على طلابنا ومواكبة تكوينهم.",
    "companies.recruitment.title": "خدمة التوظيف الدولي",
    "companies.recruitment.desc": "يمتلك IPFPSP رؤية دولية، ونقدم خدمات الوساطة في التوظيف لربط خريجينا بفرص عمل بالخارج، خاصة في أوروبا. لدينا قنوات تواصل مع مؤسسات صحية في ألمانيا ودول أخرى تعاني من نقص في موارد التمريض والصحة.",
    "companies.description2": "نوفر للشركات برامج تدريبية مخصصة وشراكات تتناسب مع احتياجاتها. على سبيل المثال، ننظم دورات خاصة داخل الشركات، ونتعاون مع دور رعاية المسنين والعيادات، كما نقدم خدمات خاصة لأصحاب العمل لدعم مؤسساتهم في تطوير الكفاءات، لا سيما في قطاع الرعاية الصحية.",

    "registration.title": "التسجيل",
    "registration.step1.title": "تقديم الطلب",
    "registration.step1.desc": "يجب على المهتمين الالتحاق بالمعهد ملء استمارة التسجيل المتاحة إما على الموقع الإلكتروني للمعهد أو مباشرة في مقر الإدارة بفاس. يُرفَق بالاستمارة عدد من الوثائق الضرورية: صورة شمسية، نسخة من بطاقة التعريف الوطنية (أو جواز السفر للطلبة الأجانب)، نسخ مصادق عليها من الشهادات التعليمية المحصلة (شهادة البكالوريا أو شهادة السنة الثالثة إعدادي حسب متطلبات البرنامج)، وكشف نقط آخر سنة دراسية. كما يُنصح بتضمين رسالة دافع توضح فيها أسباب اختياركم لهذا التكوين وأهدافكم المستقبلية.",
    "registration.step2.title": "دراسة الملف",
    "registration.step2.desc": "بعد تلقي الملفات، تقوم لجنة القبول المختصة بدراسة كل ملف بعناية. ننظر في المستوى الدراسي للمرشح والتخصص المطلوب، ونتأكد من استيفاء شروط الالتحاق الدنيا.",
    "registration.step3.title": "امتحان أو مقابلة القبول",
    "registration.step3.desc": "بناءً على البرنامج المختار ونتائج دراسة الملف، قد يُدعى بعض المرشحين لاجتياز امتحان كتابي أو مقابلة شخصية كمرحلة انتقائية. الهدف من ذلك هو تقييم قدرات المرشح ومهاراته الأساسية ومدى ملاءمته للتكوين.",
    "registration.step4.title": "القبول النهائي والتسجيل الإداري",
    "registration.step4.desc": "يتم إشعار المرشحين الذين اجتازوا جميع المراحل بنجاح بقرار القبول النهائي عبر الهاتف أو البريد الإلكتروني، ويُنشر كذلك لوائح المقبولين بمقر المعهد. في هذه المرحلة، يتوجب على المرشح المقبول استكمال إجراءات التسجيل الإداري: أداء رسوم التسجيل ورسوم الدراسة (أو على الأقل دفعة مقدمة حسب نظام الأداء المعتمد)، وتقديم النسخ الأصلية من الوثائق المطلوبة للمطابقة.",

    "faq.title": "الأسئلة الشائعة",
    "faq.q1.question": "ما هي شروط الالتحاق بالمعهد؟",
    "faq.q1.answer": "تختلف شروط القبول باختلاف البرنامج. بشكل عام، يشترط لبعض التخصصات الحصول على شهادة البكالوريا (الثانوية العامة) كحد أدنى، خاصةً البرامج ذات المستوى التقني المتخصص مثل التمريض المتعدد التخصصات أو العلاج الطبيعي. في المقابل، هناك تخصصات يمكن الولوج إليها بمستوى دراسي أقل؛ فمثلًا برنامج مساعد الممرض مفتوح ابتداءً من شهادة السنة الثالثة إعدادي (نهاية التعليم الإعدادي).",
    "faq.q2.question": "ما مدة الدراسة في البرامج المختلفة؟",
    "faq.q2.answer": "تتراوح مدة التكوين حسب البرنامج. لدينا برامج قصيرة لمدة سنة واحدة (مثل السكرتارية الطبية)، وبرامج تمتد لسنتين (مثل تكوين تقني المختبر أو مساعد الممرض)، إضافة إلى برامج طويلة تمتد لثلاث سنوات (مثل تكوين الممرض المتعدد التخصصات وأخصائي العلاج الطبيعي).",
    "faq.q3.question": "هل شهادة المعهد معترف بها من قبل الدولة؟",
    "faq.q3.answer": "نعم، شهادات المعهد معترف بها رسميًا. IPFPSP هو معهد مرخص من طرف الدولة (رقم الترخيص 5/0/2025)، وبالتالي فإن الدبلومات التي يمنحها تحمل الختم الرسمي لوزارة التربية الوطنية. هذا يعني أن خريجينا يمكنهم العمل بشهاداتهم داخل المغرب دون حاجة لأي معادلة إضافية.",
    "faq.q4.question": "هل يوفر المعهد تداريب ميدانية أو مساعدة في إيجاد عمل بعد التخرج؟",
    "faq.q4.answer": "بالتأكيد. التدريب الميداني جزء أساسي من كل برنامج تدريسي نقدمه، إذ لا يمكن تصور تكوين مهني في الصحة دون احتكاك مباشر بالواقع العملي. كما ذكرنا، نقوم بتنسيق فترات تدريبية لطلابنا في مؤسسات صحية شريكة، حيث يعمل الطالب جنبًا إلى جنب مع الطاقم الطبي الحقيقي.",
    "faq.q5.question": "هل تقدمون دورات لغة للمساعدة في العمل بالخارج (مثلاً في ألمانيا)؟",
    "faq.q5.answer": "نعم، نحن نوفر دورات لغة كما هو مفصل في قسم دورات اللغة. حرصًا منا على دعم طلابنا وخريجينا الراغبين في تطوير مسارهم المهني دوليًا، نركز بشكل خاص على دورات اللغة الألمانية. هذه الدورات ليست لتعليم اللغة فحسب، بل تشمل أيضًا جوانب ثقافية ومهنية لتجهيز المترشح للعمل أو الدراسة في بيئة ناطقة بالألمانية.",
    "faq.q6.question": "متى يبدأ العام الدراسي وكيف يمكنني التسجيل؟",
    "faq.q6.answer": "يبدأ العام الدراسي لدينا عادةً مع بداية فصل الخريف، أي في شهر سبتمبر من كل سنة. أما التسجيل، فيُفتح مسبقًا بفترة كافية – غالبًا خلال فصل الربيع أو في أوائل الصيف – وذلك لإتاحة الوقت لمعالجة طلبات القبول. ننصح كل من يرغب بالالتحاق أن يبادر بتقديم طلبه بمجرد الإعلان عن فتح باب التسجيل، حيث إن عدد المقاعد محدود ويتم البت في الطلبات حسب أسبقية التقديم واستيفاء الشروط.",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.programs": "Programmes",
    "nav.certifications": "Certifications",
    "nav.about": "À propos",
    "nav.contact": "Nous contacter",
    "nav.elearning": "E-learning",

    "hero.title": "Institut de Formation Professionnelle",
    "hero.subtitle": "Ouvrez les portes de votre avenir grâce à une formation certifiée en langues et soins infirmiers reconnue internationalement",
    "hero.cta": "Commencez votre parcours",
    "hero.location": "Fès, Maroc",
    "hero.certified": "Certifié et Accrédité",
    "hero.graduates": "Diplômés satisfaits",
    "hero.experience": "Années d'expérience",
    "hero.successRate": "Taux de réussite",

    "programs.title": "Nos Programmes",
    "programs.languages": "Programme de Langues",
    "programs.languages.desc": "Apprenez les langues étrangères selon un cursus reconnu internationalement",
    "programs.nursing": "Programme d'Infirmerie",
    "programs.nursing.desc": "Formation infirmière avancée certifiée et conforme aux normes mondiales",
    "programs.english": "Anglais",
    "programs.french": "Français",
    "programs.spanish": "Espagnol",
    "programs.clinical": "Formation Clinique",
    "programs.standards": "Normes Internationales",
    "programs.certification": "Prêt pour la Certification",
    "programs.learn": "En Savoir Plus",
    "programs.why": "Pourquoi Choisir IPFPSP-FES?",
    "programs.experts": "Enseignants Experts",
    "programs.smallClasses": "Petites Classes",
    "programs.modern": "Curriculum Moderne",
    "programs.certified": "Programmes Certifiés",
    "programs.excellence": "Excellence en éducation avec normes internationales et méthodes d'enseignement modernes",

    "certs.title": "Reconnu Internationalement",
    "certs.international": "Certifications reconnues mondialement",
    "certs.standards": "Normes éducatives mondiales",
    "certs.opportunities": "Opportunités d'emploi mondiales",
    "certs.recognized": "Reconnu par les organismes d'éducation internationaux et les employeurs du monde entier",
    "certs.curriculum": "Curriculum aligné avec les normes de l'UE et les normes éducatives internationales",
    "certs.graduates": "Les diplômés trouvent des opportunités d'emploi en Europe et au Moyen-Orient",
    "certs.subtitle":
      "Nos certifications et accréditations assurent la qualité de l'éducation et la reconnaissance mondiale",
    "certs.accredited": "Accrédité par",

    "enroll.title": "Inscrivez-vous Aujourd'hui",
    "enroll.desc": "Rejoignez des centaines d'étudiants satisfaits qui ont commencé leur parcours avec nous et ont réussi à réaliser leurs rêves",
    "enroll.button": "Demander l'admission",
    "enroll.contact": "Ou nous contacter",
    "enroll.phone": "+212 6 30 99 50 44",
    "enroll.email": "ipfpsp@gmail.com",
    "enroll.getInTouch": "Nous Contacter",
    "enroll.questions":
      "Vous avez des questions sur nos programmes ? N'hésitez pas ! Notre équipe d'admission est là pour vous accompagner à chaque étape de votre parcours éducatif.",
    "enroll.phone.label": "Téléphone",
    "enroll.email.label": "E-mail",
    "enroll.location": "Localisation",
    "enroll.support": "Support Disponible 24/7",
    "enroll.response": "Temps de Réponse 1-2 Heures",
    "enroll.fullName": "Nom Complet",
    "enroll.fullName.placeholder": "Votre nom complet",
    "enroll.email.placeholder": "votre@email.com",
    "enroll.phone.placeholder": "+212 ...",
    "enroll.program": "Programme Intéressé",
    "enroll.program.select": "Sélectionnez un programme",
    "enroll.program.languages": "Programme de Langues",
    "enroll.program.nursing": "Programme d'Infirmerie",
    "enroll.program.both": "Les Deux Programmes",
    "enroll.message": "Message",
    "enroll.message.placeholder": "Parlez-nous de vous...",
    "enroll.submit": "Soumettre",
    "enroll.thanks": "Merci!",
    "enroll.thanks.message": "Nous avons reçu votre demande et vous contacterons bientôt.",
    "enroll.contact.within": "Nous vous contacterons dans les 24 heures",

    "footer.about": "À Propos",
    "footer.programs": "Programmes",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés © 2025",
    "footer.description":
      "Institut d'éducation leader pour l'enseignement des langues et des soins infirmiers à Fès, Maroc. Certifié pour les opportunités internationales.",
    "footer.mission": "Notre Mission",
    "footer.team": "Notre Équipe",
    "footer.stories": "Histoires de Succès",
    "footer.blog": "Blog",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.cookies": "Cookies",
    "footer.location": "Fès, Maroc",

    institution_name: "Institut Privé de Formation Professionnelle en Santé et Soins Paramédicaux",
    authorization_date: "L'établissement est autorisé par l'État sous le n° 5/0/2025",

    program1_name: "Infirmier Polyvalent",
    program1_level: "Niveau Baccalauréat - Toutes Spécialités",
    program1_duration: "Durée de la Formation",
    program1_requirement: "Niveau Scolaire Requis",
    program1_years: "3 Ans",

    program2_name: "Aide Soignant",
    program2_level: "Niveau 3ème Année Collège",
    program2_duration: "Durée de la Formation",
    program2_requirement: "Niveau Scolaire Requis",
    program2_years: "1 An",

    education_level: "Niveau d'Éducation",
    admission_requirement: "Conditions d'Admission",
    training_duration: "Durée de la Formation",
    enroll_now: "S'Inscrire Maintenant",
    contact_us: "Nous Contacter",
    follow_us: "Nous Suivre",
    officially_authorized: "Officiellement Autorisé par le Ministère de l'Éducation Marocain",

    "contact.workingHours": "Horaires d'Ouverture",
    "contact.weekdays": "Lundi - Vendredi: 8:00 - 18:00",
    "contact.saturday": "Samedi: 10:00 - 14:00",
    "contact.emergency": "Cas urgents:",
    "contact.germanLessons": "Cours d'Allemand",
    "contact.nursingCourses": "Cours d'Infirmerie",
    "contact.jobsGermany": "Questions sur l'emploi et la formation en Allemagne",
    "contact.germanNumber": "+49 174 77 80 532",
    "contact.nursingNumber": "+212 7 79 74 75 29",
    "contact.germanJobsNumber": "+212 34 43 61 00",
    "contact.germanLessonsNumber": "+212 6 30 99 50 44",
    "contact.important": "Pour les cas importants et les demandes de renseignements",
    "contact.address": "Résidence Bureau Riad Salam n° 3, Lotissement Moulins El Idrissia, Avenue des F.A.R., Fès, Maroc",
    "contact.phone": "+212 5 35 94 34 68",
    "contact.whatsapp": "+49 174 7780532",
    "contact.email": "info@ipfpsp.ma",

    "about.title": "À propos de nous",
    "about.description": "Bienvenue à l'IPFPSP ! Nous sommes un établissement privé d'enseignement professionnel situé au cœur de Fès, spécialisé dans la formation aux métiers de la santé et du paramédical. Autorisé par l'État (n° 5/0/2025), nous sommes fiers de proposer des formations de haute qualité qui respectent les normes nationales et internationales. Notre mission ? Former des professionnels de santé compétents, passionnés et prêts à intégrer le monde du travail, que ce soit au Maroc ou à l'étranger.",
    "about.description2": "Ce qui nous distingue à l'IPFPSP, c'est notre approche qui allie parfaitement théorie et pratique. Nos étudiants bénéficient de cours théoriques dispensés par des formateurs expérimentés, d'un entraînement pratique intensif dans nos laboratoires modernes, et de stages réels dans des hôpitaux et centres de santé partenaires. Tout cela pour garantir que nos diplômés sont prêts à travailler dès leur sortie. Nous accueillons des étudiants du Maroc et de l'étranger, offrons un accompagnement spécial aux étudiants internationaux, et préparons ceux qui souhaitent travailler à l'étranger, notamment en Allemagne où la demande en personnel de santé est très forte.",

    "vision.title": "Vision",
    "vision.description": "Notre vision est simple et claire : devenir le centre de référence en formation santé et paramédical, non seulement au Maroc mais aussi à l'international. Nous rêvons d'un système de santé meilleur, et nous croyons que cela commence par former des professionnels hautement qualifiés qui allient compétence technique et valeurs humaines. Nous voulons un environnement où chaque étudiant peut s'épanouir, développer son potentiel et devenir un leader dans son domaine. Nous construisons des partenariats internationaux et adoptons les meilleures pratiques mondiales, pour que nos diplômés soient des ambassadeurs de l'excellence partout où ils vont.",

    "values.title": "Valeurs",
    "values.excellence.title": "Excellence académique",
    "values.excellence.desc": "La qualité de l'enseignement est notre priorité absolue. Nous recrutons des formateurs qualifiés et expérimentés (infirmiers cadres, médecins, spécialistes…) et nous veillons à ce que nos programmes soient régulièrement mis à jour. L'institut s'aligne sur les standards internationaux de formation (notamment ceux de l'OMS et de l'UNESCO en matière de formation technique et professionnelle) afin d'assurer une solide maîtrise des compétences par nos élèves.",
    "values.professionalism.title": "Éthique et professionnalisme",
    "values.professionalism.desc": "Nous inculquons à nos étudiants le respect de la déontologie professionnelle, élément indispensable dans les métiers de la santé. Cela passe par le respect du secret médical, l'intégrité, l'assiduité et le sens des responsabilités. Au-delà de la maîtrise technique, nous formons des professionnels fiables, sur qui patients et collègues pourront compter.",
    "values.humanity.title": "Compassion & humanité",
    "values.humanity.desc": "Comprendre et ressentir les besoins d'autrui est au cœur des professions de santé. Nous valorisons la compassion, l'écoute et l'empathie. Ces qualités humaines sont cultivées à travers des modules de communication soignant-patient, des jeux de rôle et l'exemple que donnent nos formateurs.",
    "values.innovation.title": "Innovation pédagogique",
    "values.innovation.desc": "Conscients que le domaine de la santé évolue rapidement, nous adoptons des méthodes pédagogiques modernes et dynamiques. Apprentissage par simulation, études de cas cliniques, utilisation d'outils multimédias interactifs – autant de techniques que nous intégrons dans notre enseignement pour stimuler l'engagement des étudiants et développer leur esprit critique.",
    "values.openness.title": "Ouverture & diversité",
    "values.openness.desc": "L'IPFPSP accueille des étudiants de divers horizons socio-culturels et promeut un climat d'inclusion et de respect mutuel. Nous croyons que la diversité est une richesse qui prépare nos étudiants à travailler dans n'importe quel contexte, au Maroc ou à l'étranger.",

    "campus.title": "Campus",
    "campus.description": "Notre campus, situé dans un quartier accessible de Fès, offre un cadre d'étude optimal, alliant confort, modernité et fonctionnalité. Les locaux de l'IPFPSP comprennent des salles de cours spacieuses et équipées de matériel pédagogique moderne (projecteurs, tableaux interactifs) pour faciliter le processus d'apprentissage et encourager l'interaction entre formateurs et étudiants.",
    "campus.description2": "Des laboratoires spécialisés : nous disposons par exemple d'un laboratoire d'anatomie/physiologie pour l'étude pratique du corps humain, d'une salle de simulation de soins infirmiers (avec mannequins médicaux haute-fidélité pour pratiquer des gestes techniques en conditions quasi réelles), ainsi que d'un laboratoire d'analyses pour les formations de techniciens de laboratoire. Une bibliothèque dotée d'un large fonds documentaire en sciences de la santé (ouvrages, revues spécialisées, ressources numériques).",
    "campus.facility1.title": "Salles de cours équipées",
    "campus.facility1.desc": "Salles de cours spacieuses et équipées de matériel pédagogique moderne",
    "campus.facility2.title": "Laboratoires spécialisés",
    "campus.facility2.desc": "Laboratoire d'anatomie/physiologie et salle de simulation de soins infirmiers",
    "campus.facility3.title": "Bibliothèque",
    "campus.facility3.desc": "Bibliothèque dotée d'un large fonds documentaire en sciences de la santé",
    "campus.facility4.title": "Espaces informatiques",
    "campus.facility4.desc": "Coin informatique pour consulter des bases de données en ligne",
    "campus.facility5.title": "Espaces communs",
    "campus.facility5.desc": "Espaces communs conviviaux pour se détendre et échanger",

    "programs.delegue.title": "Délégué Médical",
    "programs.delegue.desc": "La formation de Délégué Médical prépare les participants à travailler en tant que représentants médicaux dans l'industrie pharmaceutique. Ils apprennent à présenter professionnellement des médicaments et produits médicaux et à assurer la liaison entre les laboratoires pharmaceutiques et les professionnels de la santé.",
    "programs.pedagogique.title": "Formation Pédagogique",
    "programs.pedagogique.desc": "La Formation Pédagogique vise à former les participants aux métiers de l'éducation dans les écoles maternelles et primaires. Les apprenants acquièrent des bases en psychologie du développement, en didactique et en prise en charge d'enfants afin de travailler professionnellement avec les enfants dans le milieu éducatif.",
    "programs.paramedical.title": "Paramédical",
    "programs.paramedical.desc": "La formation Paramédicale offre aux participants les connaissances et compétences de base dans le domaine de la santé. Elle prépare les apprenants à effectuer des tâches de soutien médical et à intégrer des équipes de soins aux côtés des professionnels de santé.",
    "programs.koch.title": "Cuisine (Koch)",
    "programs.koch.desc": "La formation Cuisine (Koch) enseigne aux participants l'art culinaire et l'organisation d'une cuisine professionnelle. Grâce à une formation pratique, ils apprennent les techniques de base de la cuisine, la planification de menus ainsi que les normes d'hygiène, afin de pouvoir exercer avec succès comme cuisiniers dans la restauration ou l'hôtellerie.",
    "programs.premiers_secours.title": "Séances instructives de premiers secours",
    "programs.premiers_secours.desc": "Les séances instructives de premiers secours sont des cours de secourisme où les participants acquièrent les gestes de base qui sauvent des vies. À travers des exercices pratiques, ils apprennent à réagir correctement en situation d'urgence et à assister les blessés en attendant l'arrivée des secours professionnels.",
    "programs.bureautique.title": "Bureautique",
    "programs.bureautique.desc": "La formation Bureautique dote les apprenants des compétences de base en informatique de bureau et en organisation administrative. Ils apprennent à utiliser efficacement les logiciels courants tels que la suite Microsoft Office (Word, Excel, PowerPoint, Outlook) et acquièrent des compétences organisationnelles afin d'accomplir efficacement les tâches de bureau.",
    "programs.physiotherapie.title": "Kinésithérapeute",
    "programs.physiotherapie.desc": "Cette filière forme des spécialistes de la rééducation physique. Le cursus comprend l'étude de la biomécanique, des techniques de massage et de mobilisation, de la physiothérapie (électrothérapie, hydrothérapie…) et de la kinésithérapie respiratoire, entre autres.",
    "programs.laboratoire.title": "Technicien(ne) de Laboratoire",
    "programs.laboratoire.desc": "Ce programme prépare les étudiants aux métiers des analyses biomédicales. Le contenu pédagogique couvre la microbiologie, l'hématologie, la biochimie, l'immunologie, etc. Les travaux pratiques sont réalisés en laboratoire où les étudiants apprennent à manipuler des échantillons (sang, urine, tissus) et à utiliser les automates d'analyse en respectant les protocoles de sécurité et d'hygiène.",
    "programs.secretaire.title": "Secrétaire Médical(e)",
    "programs.secretaire.desc": "Cette formation est axée sur l'acquisition de compétences administratives et relationnelles spécifiques au milieu médical. Le programme inclut la terminologie médicale, la gestion des dossiers patients, les bases en comptabilité et facturation des actes médicaux, ainsi que l'initiation à la législation sanitaire.",

    "diplomas.title": "Diplômes",
    "diplomas.description": "Les diplômes délivrés par l'IPFPSP sont accrédités par l'État marocain, gage de leur fiabilité et de leur crédibilité sur le marché du travail. Grâce à l'autorisation officielle n° 5/0/2025 qui nous a été accordée, nos certifications répondent pleinement aux critères du Ministère de l'Éducation.",
    "diplomas.description2": "Au-delà de cet ancrage national, nous nous efforçons de donner à nos diplômes une dimension internationale. Nos programmes sont élaborés en référence aux standards éducatifs internationaux : par exemple, nous suivons les recommandations de l'OMS pour la formation des infirmiers (concernant le nombre d'heures de pratique, les compétences devant être maîtrisées, etc.) et nous nous inspirons du cadre de la UNESCO en matière de formation technique et professionnelle (TVET) pour aligner nos filières sur les compétences clés demandées mondialement.",

    "languages.title": "Cours de langues",
    "languages.description": "Conscients de l'importance des langues étrangères dans le parcours d'un professionnel de santé moderne, nous proposons à l'IPFPSP des cours de langues optionnels pour compléter la formation de nos étudiants. Ces cours, adaptés au contexte médical, visent à renforcer l'employabilité et l'ouverture d'esprit de nos futurs diplômés.",
    "languages.german.title": "Cours d'allemand",
    "languages.german.desc": "Nous offrons un programme d'allemand médical progressif, depuis les bases jusqu'au niveau B2 du Cadre Européen Commun de Référence pour les Langues (CECR). L'objectif principal est de permettre aux participants de communiquer efficacement en allemand dans un contexte de soins. Le contenu couvre le vocabulaire général et médical, la grammaire, mais aussi des mises en situation professionnelles.",
    "languages.german.levels": "Nous proposons des cours d'allemand pour tous les niveaux de A1 à C1. Nous offrons également des cours de préparation aux examens reconnus (Telc, ÖSD ainsi que les certifications du Goethe-Institut) afin de préparer efficacement les participants aux certificats de langue officiels.",
    "languages.english.title": "Cours d'anglais",
    "languages.english.desc": "L'anglais étant la lingua franca de la communauté scientifique et internationale, nous proposons des cours d'anglais axés sur la communication en milieu médical et la lecture de documents scientifiques. Les étudiants pratiquent l'anglais oral (pour échanger avec des patients étrangers ou des collègues anglophones) et l'anglais écrit (rédaction de courriels professionnels, compréhension d'articles de recherche, etc.).",
    "languages.english.levels": "Nous proposons des cours d'anglais pour tous les niveaux de A1 à C1. Des cours de préparation aux examens internationaux, tels que le TOEFL et l'IELTS, sont également disponibles afin d'aider les participants à réussir ces tests et obtenir des certifications reconnues.",
    "languages.french.title": "Cours de français",
    "languages.french.desc": "Bien que la plupart de nos étudiants maîtrisent déjà le français, nous tenons à offrir un soutien supplémentaire à ceux pour qui ce n'est pas la langue maternelle (par exemple, des étudiants venant de pays non francophones d'Afrique). Ce cours de français vise à renforcer la capacité à étudier et travailler en français.",
    "languages.french.levels": "Nous proposons des cours de français pour tous les niveaux de A1 à C1. Si nécessaire, nous offrons également des cours de préparation aux examens officiels de français tels que le DELF/DALF, afin d'aider les participants à obtenir des certifications reconnues en langue française.",

    "online.title": "Apprentissage en ligne",
    "online.description": "Dans le but de rendre la formation plus flexible et d'intégrer les avantages des nouvelles technologies, l'IPFPSP a mis en place un système d'apprentissage en ligne complémentaire à l'enseignement en présentiel. Grâce à notre plateforme e-learning dédiée, nos étudiants peuvent accéder à une multitude de ressources pédagogiques à tout moment et depuis n'importe quel lieu.",
    "online.description2": "Certaines unités d'enseignement, en particulier celles de culture générale ou d'introduction, peuvent être suivies en mode hybride. Par exemple, un cours d'informatique médicale ou d'anglais technique pourrait être dispensé en partie en ligne. Cela réduit le temps de présence obligatoire sur le campus et offre plus de souplesse aux étudiants dans l'organisation de leur emploi du temps, sans compromis sur la qualité de l'apprentissage.",
    "online.allCourses": "Tous nos cours sont également proposés en ligne, ce qui vous permet d'apprendre avec flexibilité depuis votre domicile ou n'importe où ailleurs. Nous utilisons des plateformes d'apprentissage en ligne modernes et des supports numériques afin de garantir une expérience d'apprentissage interactive et efficace.",

    "companies.title": "Offres pour les entreprises",
    "companies.description": "L'IPFPSP s'attache à développer des partenariats et des services à destination des entreprises et des organisations du secteur de la santé, afin de renforcer les liens entre la formation et l'emploi et de contribuer à l'amélioration continue des pratiques professionnelles.",
    "companies.training.title": "Formations continues sur mesure",
    "companies.training.desc": "Nous concevons des programmes de formation continue adaptés aux besoins spécifiques des hôpitaux, cliniques, centres de soins ou même d'autres structures (associations, ONG, entreprises disposant d'un service médical interne). Par exemple, nous pouvons organiser des ateliers de remise à niveau en hygiène hospitalière pour le personnel soignant.",
    "companies.partnerships.title": "Partenariats d'insertion internationale",
    "companies.partnerships.desc": "Conscients des besoins en ressources humaines qualifiées dans le domaine de la santé, nous facilitons la mise en relation entre nos diplômés et les recruteurs. Les entreprises du secteur médical (hôpitaux, cliniques privées, laboratoires, maisons de retraite…) peuvent nous contacter pour diffuser leurs offres d'emploi auprès de nos anciens étudiants.",
    "companies.recruitment.title": "Recrutement et journées carrières",
    "companies.recruitment.desc": "L'IPFPSP se positionne comme intermédiaire de recrutement international. En pratique, cela signifie que nous avons établi des collaborations avec des agences de recrutement ou des établissements de santé à l'étranger (notamment en Europe). Par exemple, pour l'Allemagne, nous travaillons avec des partenaires qui recherchent du personnel infirmier ou aide-soignant.",
    "companies.description2": "Nous offrons aux entreprises des formations sur mesure et des partenariats adaptés à leurs besoins. Par exemple, nous organisons des cours en entreprise, collaborons avec des maisons de retraite et des cliniques, et fournissons des services aux employeurs afin de soutenir le développement du personnel de leurs établissements, en particulier dans le secteur des soins et de la santé.",

    "registration.title": "Inscription",
    "registration.step1.title": "Dépôt de candidature",
    "registration.step1.desc": "Les candidats doivent d'abord remplir le dossier de candidature (formulaire d'inscription) disponible en ligne sur notre site ou en format papier à retirer à l'accueil de l'institut. Ce dossier comprend un formulaire à renseigner avec vos coordonnées et le choix de la filière souhaitée, ainsi que la liste des pièces justificatives à fournir : copie légalisée de la carte d'identité (ou passeport pour les étrangers), copies certifiées conformes des diplômes et relevés de notes (par ex. attestation du Baccalauréat ou du Brevet, selon les exigences du programme), certificats médicaux (si requis pour certaines filières), 4 photos d'identité récentes, et éventuellement une lettre de motivation.",
    "registration.step2.title": "Étude du dossier",
    "registration.step2.desc": "Une fois le dossier déposé, notre commission d'admission examine attentivement chaque candidature. Les critères principaux sont le niveau académique (par exemple, être titulaire du Baccalauréat pour les formations de niveau Technicien Spécialisé, ou d'un niveau 3ème collège pour certaines formations qualifiantes), l'âge du candidat (habituellement entre 17 et 30 ans pour l'entrée en formation initiale, des exceptions peuvent s'appliquer), ainsi que l'adéquation du profil du candidat avec les exigences du métier visé.",
    "registration.step3.title": "Sélection (tests ou entretien)",
    "registration.step3.desc": "Selon la filière et en cas d'un nombre de candidatures élevé, une sélection peut être organisée. Cela peut prendre la forme d'un test écrit (évaluation des connaissances de base en biologie, français, etc., et éventuellement un test psychotechnique) ou d'un entretien oral avec un jury (composé de formateurs et de professionnels) visant à évaluer la motivation du candidat, sa compréhension du métier et sa capacité à suivre la formation.",
    "registration.step4.title": "Admission et inscription définitive",
    "registration.step4.desc": "Après les étapes précédentes, les candidats retenus reçoivent une lettre d'admission officielle de l'IPFPSP. Ils sont alors invités à venir procéder à leur inscription administrative définitive. Celle-ci comprend le paiement des frais d'inscription (droits d'inscription annuels et éventuellement acompte sur la scolarité selon les modalités établies), la remise des documents originaux pour vérification (notamment le diplôme du Baccalauréat original pour inscription au registre de l'institut), et la signature du règlement intérieur et du contrat de formation.",

    "faq.title": "FAQ (Foire aux questions)",
    "faq.q1.question": "Quelles sont les conditions d'admission ?",
    "faq.q1.answer": "Les conditions d'admission varient en fonction de la filière choisie. De manière générale, pour les formations de niveau Technicien Spécialisé (comme Infirmier Polyvalent, Kinésithérapeute, etc.), il est requis d'être titulaire du Baccalauréat (toutes séries confondues, bien qu'un bac scientifique soit un plus) ou d'un diplôme reconnu équivalent. En revanche, certaines formations qualifiantes plus courtes (par exemple Aide-soignant(e) ou Secrétaire Médicale) sont accessibles avec un niveau scolaire de 3ème année secondaire collège (Brevet) réussi.",
    "faq.q2.question": "Quelle est la durée des formations ?",
    "faq.q2.answer": "La durée de nos formations dépend de la filière. Nos principaux programmes se répartissent ainsi : les formations de Technicien Spécialisé (Infirmier Polyvalent, Kinésithérapeute…) s'étalent sur 3 ans (6 semestres), les formations de Technicien (comme Technicien de Laboratoire) durent 2 ans (4 semestres), et nos formations qualifiantes (Aide-soignant, Secrétaire Médicale) se complètent en 1 an (2 semestres).",
    "faq.q3.question": "Les diplômes sont-ils reconnus par l'État ?",
    "faq.q3.answer": "Oui, absolument. Tous les diplômes décernés par l'IPFPSP sont reconnus par l'État marocain. Notre autorisation n° 5/0/2025 garantit que nous respectons le cahier des charges du Ministère de l'Éducation pour chaque filière, et que nos diplômés reçoivent un titre officiellement enregistré.",
    "faq.q4.question": "Y a-t-il des stages pratiques et un accompagnement vers l'emploi ?",
    "faq.q4.answer": "Oui, bien sûr. Les stages pratiques sont au cœur de notre pédagogie. Comme indiqué précédemment, chaque étudiant effectue plusieurs stages encadrés durant sa formation. L'IPFPSP a signé des accords avec un réseau d'établissements de soins (à Fès et dans les régions avoisinantes) afin de placer nos étudiants dans des contextes variés et formateurs.",
    "faq.q5.question": "Proposez-vous des cours de langues, notamment pour partir à l'étranger ?",
    "faq.q5.answer": "Oui, l'IPFPSP propose des cours de langues (facultatifs mais fortement recommandés) pour compléter votre formation. Le cours d'allemand est particulièrement prisé, car de nombreux étudiants envisagent de travailler en Allemagne où la demande en soignants est élevée. Ce cours vous permettra d'atteindre un niveau B2 et d'acquérir le vocabulaire médical allemand, ce qui est un atout majeur si vous souhaitez vous expatrier.",
    "faq.q6.question": "Quand débutent les cours et comment s'inscrire ?",
    "faq.q6.answer": "La rentrée académique à l'IPFPSP a lieu généralement au début du mois de septembre pour l'ensemble des filières. Des sessions d'accueil et d'orientation sont prévues pour les nouveaux étudiants afin de les familiariser avec l'établissement, le personnel enseignant et le fonctionnement des cours. Avant cela, la campagne d'inscription s'ouvre en général au printemps (aux environs d'avril ou mai).",
  },
  de: {
    "nav.home": "Startseite",
    "nav.programs": "Programme",
    "nav.certifications": "Zertifizierungen",
    "nav.about": "Über Uns",
    "nav.contact": "Kontakt",
    "nav.elearning": "E-Learning",

    "hero.title": "Institut für Berufsbildung",
    "hero.subtitle": "Öffnen Sie die Türen zu Ihrer Zukunft mit zertifizierter Ausbildung in Sprachen und Krankenpflege, international anerkannt",
    "hero.cta": "Starten Sie Ihre Reise",
    "hero.location": "Fes, Marokko",
    "hero.certified": "Offiziell zertifiziert",
    "hero.graduates": "Zufriedene Absolventen",
    "hero.experience": "Jahre Erfahrung",
    "hero.successRate": "Erfolgsquote",

    "programs.title": "Unsere Programme",
    "programs.languages": "Sprachenprogramm",
    "programs.languages.desc": "Erlernen Sie Fremdsprachen nach einem international anerkannten Lehrplan",
    "programs.nursing": "Krankenpflegeprogramm",
    "programs.nursing.desc":
      "Fortgeschrittene Krankenpflegeausbildung, zertifiziert und nach internationalen Standards",
    "programs.english": "Englisch",
    "programs.french": "Französisch",
    "programs.spanish": "Spanisch",
    "programs.clinical": "Klinische Ausbildung",
    "programs.standards": "Internationale Standards",
    "programs.certification": "Zertifizierungsreif",
    "programs.learn": "Mehr Erfahren",
    "programs.why": "Warum IPFPSP-FES Wählen?",
    "programs.experts": "Fachlehrer",
    "programs.smallClasses": "Kleine Klassen",
    "programs.modern": "Moderner Lehrplan",
    "programs.certified": "Zertifizierte Programme",
    "programs.excellence": "Exzellenz in der Bildung mit internationalen Standards und modernen Lehrmethoden",

    "certs.title": "International Anerkannt",
    "certs.international": "Weltweit anerkannte Zertifizierungen",
    "certs.standards": "Internationale Bildungsstandards",
    "certs.opportunities": "Weltweite Beschäftigungsmöglichkeiten",
    "certs.recognized": "Anerkannt von internationalen Bildungsorganisationen und Arbeitgebern weltweit",
    "certs.curriculum": "Lehrplan abgestimmt auf EU- und internationale Bildungsstandards",
    "certs.graduates": "Absolventen finden Beschäftigungsmöglichkeiten in Europa und dem Nahen Osten",
    "certs.subtitle":
      "Unsere Zertifizierungen und Akkreditierungen gewährleisten Bildungsqualität und globale Anerkennung",
    "certs.accredited": "Akkreditiert von",

    "enroll.title": "Melden Sie sich heute an",
    "enroll.desc": "Treten Sie hunderten von zufriedenen Studierenden bei, die ihre Reise mit uns begonnen haben und ihre Träume verwirklicht haben",
    "enroll.button": "Bewerbung einreichen",
    "enroll.contact": "Oder kontaktieren Sie uns",
    "enroll.phone": "+212 6 30 99 50 44",
    "enroll.email": "ipfpsp@gmail.com",
    "enroll.getInTouch": "Kontaktieren Sie uns",
    "enroll.questions":
      "Haben Sie Fragen zu unseren Programmen? Zögern Sie nicht! Unser Zulassungsteam ist da, um Sie bei jedem Schritt Ihrer Bildungsreise zu unterstützen.",
    "enroll.phone.label": "Telefon",
    "enroll.email.label": "E-Mail",
    "enroll.location": "Ort",
    "enroll.support": "Support verfügbar 24/7",
    "enroll.response": "Antwortzeit 1-2 Stunden",
    "enroll.fullName": "Vollständiger Name",
    "enroll.fullName.placeholder": "Ihr vollständiger Name",
    "enroll.email.placeholder": "ihre@email.com",
    "enroll.phone.placeholder": "+212 ...",
    "enroll.program": "Interessiertes Programm",
    "enroll.program.select": "Wählen Sie ein Programm",
    "enroll.program.languages": "Sprachenprogramm",
    "enroll.program.nursing": "Krankenpflegeprogramm",
    "enroll.program.both": "Beide Programme",
    "enroll.message": "Nachricht",
    "enroll.message.placeholder": "Erzählen Sie uns von Ihnen...",
    "enroll.submit": "Absenden",
    "enroll.thanks": "Vielen Dank!",
    "enroll.thanks.message": "Wir haben Ihre Anfrage erhalten und werden Sie bald kontaktieren.",
    "enroll.contact.within": "Wir werden Sie innerhalb von 24 Stunden kontaktieren",

    "footer.about": "Über Uns",
    "footer.programs": "Programme",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten © 2025",
    "footer.description":
      "Führendes Bildungsinstitut für Sprachen- und Krankenpflegeunterricht in Fes, Marokko. Zertifiziert für internationale Chancen.",
    "footer.mission": "Unsere Mission",
    "footer.team": "Unser Team",
    "footer.stories": "Erfolgsgeschichten",
    "footer.blog": "Blog",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Nutzungsbedingungen",
    "footer.cookies": "Cookies",
    "footer.location": "Fes, Marokko",

    institution_name: "Privates Institut für Berufsbildung in Gesundheit und Paramedizin",
    authorization_date: "Die Einrichtung ist vom Staat unter Nr. 5/0/2025 zugelassen",

    program1_name: "Universalmediziner",
    program1_level: "Abiturniveau - Alle Fachrichtungen",
    program1_duration: "Ausbildungsdauer",
    program1_requirement: "Erforderliches Schulniveau",
    program1_years: "3 Jahre",

    program2_name: "Pflegehelfer",
    program2_level: "Niveau 3. Klasse Gymnasium",
    program2_duration: "Ausbildungsdauer",
    program2_requirement: "Erforderliches Schulniveau",
    program2_years: "1 Jahr",

    education_level: "Bildungsniveau",
    admission_requirement: "Zulassungsvoraussetzungen",
    training_duration: "Ausbildungsdauer",
    enroll_now: "Jetzt Anmelden",
    contact_us: "Kontaktieren Sie uns",
    follow_us: "Folgen Sie uns",
    officially_authorized: "Offiziell vom marokkanischen Bildungsministerium genehmigt",

    "contact.workingHours": "Öffnungszeiten",
    "contact.weekdays": "Montag - Freitag: 8:00 - 18:00",
    "contact.saturday": "Samstag: 10:00 - 14:00",
    "contact.emergency": "Dringende Fälle:",
    "contact.germanLessons": "Deutschunterricht",
    "contact.nursingCourses": "Krankenpflegekurse",
    "contact.jobsGermany": "Fragen zu Arbeitsplätzen und Ausbildung in Deutschland",
    "contact.germanNumber": "+49 174 77 80 532",
    "contact.nursingNumber": "+212 7 79 74 75 29",
    "contact.germanJobsNumber": "+212 34 43 61 00",
    "contact.germanLessonsNumber": "+212 6 30 99 50 44",
    "contact.important": "Bei wichtigen Fällen und Anfragen",
    "contact.address": "Résidence Bureau Riad Salam Nr. 3, Lotissement Moulins El Idrissia, Avenue des F.A.R., Fès, Marokko",
    "contact.phone": "+212 5 35 94 34 68",
    "contact.whatsapp": "+49 174 7780532",
    "contact.email": "info@ipfpsp.ma",

    "about.title": "Über uns",
    "about.description": "Willkommen beim IPFPSP! Wir sind eine private Berufsschule für Gesundheits- und Pflegeberufe, mitten im Herzen der historischen Stadt Fès. Staatlich autorisiert (Nr. 5/0/2025), sind wir stolz darauf, praxisorientierte Ausbildungen von höchster Qualität anzubieten, die den nationalen und internationalen Standards entsprechen. Unser Ziel? Die nächste Generation von Pflege- und Gesundheitsfachkräften ausbilden, die bereit sind, sowohl in Marokko als auch international zu arbeiten.",
    "about.description2": "Was uns beim IPFPSP auszeichnet, ist unsere umfassende Ausbildung, die Theorie und Praxis perfekt verbindet. Unsere Schüler erhalten theoretischen Unterricht von erfahrenen Dozenten, intensives praktisches Training in unseren modernen Laboren und echte Praktika in Krankenhäusern und Kliniken. Alles, um sicherzustellen, dass unsere Absolventen bestens auf den Arbeitsalltag vorbereitet sind. Wir heißen nicht nur marokkanische Studierende willkommen, sondern auch internationale Interessenten – und bieten spezielle Unterstützung für ausländische Studenten und zusätzliche Programme für diejenigen, die im Ausland arbeiten möchten, besonders in Deutschland, wo der Bedarf an Gesundheitsfachkräften sehr hoch ist.",

    "vision.title": "Vision",
    "vision.description": "Unsere Vision ist einfach und klar: Wir wollen das führende Ausbildungsinstitut im Gesundheits- und Paramedizinischen Bereich werden – nicht nur in Marokko, sondern auch international. Wir träumen von einem besseren Gesundheitswesen und glauben, dass dies damit beginnt, hochqualifizierte, engagierte und empathische Fachkräfte auszubilden. Wir wollen ein Umfeld schaffen, in dem jeder Student sein Potenzial voll entfalten und ein Leader in seinem Bereich werden kann. Wir bauen internationale Partnerschaften auf und übernehmen die besten globalen Praktiken, damit unsere Absolventen überall Botschafter der Exzellenz sind.",

    "values.title": "Werte",
    "values.excellence.title": "Exzellenz",
    "values.excellence.desc": "Wir streben nach höchster Qualität in Lehre und Praxis. Kontinuierliche Verbesserung und die Einhaltung internationaler Ausbildungsstandards (z. B. Richtlinien der WHO für Gesundheitsberufe) sind für uns selbstverständlich.",
    "values.professionalism.title": "Professionalität & Ethik",
    "values.professionalism.desc": "Verantwortung, Zuverlässigkeit und berufsethisches Handeln stehen bei uns an erster Stelle. Wir vermitteln unseren Schülern Integrität und die Bedeutung der Schweigepflicht sowie den respektvollen Umgang mit Patienten.",
    "values.humanity.title": "Menschlichkeit & Empathie",
    "values.humanity.desc": "Als Ausbildungsstätte im Gesundheitswesen fördern wir Mitgefühl und humanitäre Werte. Unsere Absolventen sollen nicht nur fachlich kompetent, sondern auch empathisch mit Patienten und Angehörigen umgehen können.",
    "values.innovation.title": "Innovation",
    "values.innovation.desc": "Wir setzen auf moderne Unterrichtsmethoden und Technologie. Ob E-Learning-Plattform, Simulationstraining oder aktuelle Fachliteratur – Innovation in der Ausbildung garantiert, dass unser Lehrplan stets am Puls der Zeit ist.",
    "values.openness.title": "Offenheit & Internationalität",
    "values.openness.desc": "Wir pflegen eine Kultur der Offenheit. Unterschiedliche Hintergründe und Kulturen bereichern unseren Campus. Zudem ermutigen wir unsere Schüler, Fremdsprachen zu lernen und Erfahrungen im Ausland zu sammeln, um ihren Horizont zu erweitern.",

    "campus.title": "Campus",
    "campus.description": "Unser Campus im Herzen von Fès bietet eine moderne, gut ausgestattete Lernumgebung. Die Räumlichkeiten umfassen helle Klassenräume mit aktueller Präsentationstechnik, spezialisierte Fachräume sowie Labore für Biologie und Pflege. In unseren Skills-Labs können praktische Fertigkeiten an modernen medizinischen Simulationsmodellen und Geräten geübt werden.",
    "campus.description2": "Außerdem stehen den Schülern eine Fachbibliothek mit Literatur in mehreren Sprachen, Computerarbeitsplätze und Ruhezonen zur Verfügung. Der Campus ist verkehrsgünstig gelegen und leicht erreichbar. Sicherheit und Wohlbefinden der Studierenden haben hohe Priorität: Wir verfügen über einen betreuten Campus mit Zugangskontrollen und achten auf ein förderliches Lernklima.",
    "campus.facility1.title": "Ausgestattete Klassenzimmer",
    "campus.facility1.desc": "Helle Klassenräume mit aktueller Präsentationstechnik",
    "campus.facility2.title": "Spezialisierte Labore",
    "campus.facility2.desc": "Labore für Biologie und Pflege mit Simulationsmodellen",
    "campus.facility3.title": "Fachbibliothek",
    "campus.facility3.desc": "Fachbibliothek mit Literatur in mehreren Sprachen",
    "campus.facility4.title": "Computerarbeitsplätze",
    "campus.facility4.desc": "Computerarbeitsplätze für E-Learning",
    "campus.facility5.title": "Gemeinschaftsräume",
    "campus.facility5.desc": "Ruhezonen und Bereiche für Gruppenarbeit",

    "programs.delegue.title": "Délégué Médical",
    "programs.delegue.desc": "Die Ausbildung zum Délégué Médical bereitet darauf vor, als medizinischer Vertreter in der Pharmaindustrie zu arbeiten. Die Teilnehmer lernen, Arzneimittel und medizinische Produkte fachgerecht zu präsentieren und die Kommunikation zwischen Pharmaunternehmen und Gesundheitsdienstleistern effektiv zu gestalten.",
    "programs.pedagogique.title": "Formation Pédagogique",
    "programs.pedagogique.desc": "Die Formation Pédagogique bildet die Teilnehmer für pädagogische Tätigkeiten in Kindergärten und Schulen aus. Sie erwerben Grundlagen in Entwicklungspsychologie, Didaktik und Kinderbetreuung, um professionell mit Kindern im Bildungsbereich arbeiten zu können.",
    "programs.paramedical.title": "Paramedical",
    "programs.paramedical.desc": "Die Ausbildung Paramedical vermittelt grundlegende Kenntnisse und Fähigkeiten im Gesundheitswesen. Die Teilnehmer werden auf unterstützende Tätigkeiten im medizinischen Bereich vorbereitet, um in Teams von Pflege- und Gesundheitsfachkräften mitzuwirken.",
    "programs.koch.title": "Koch",
    "programs.koch.desc": "Die Ausbildung Koch schult die Teilnehmer in der Kunst des Kochens und der Küchenorganisation. Durch praxisorientiertes Training erlernen sie grundlegende Kochtechniken, Menüplanung und Hygienevorschriften, um erfolgreich als Koch in Gastronomie oder Hotellerie zu arbeiten.",
    "programs.premiers_secours.title": "Séances instructives de premiers secours",
    "programs.premiers_secours.desc": "Die Séances instructives de premiers secours sind Erste-Hilfe-Kurse, in denen die Teilnehmer grundlegende lebensrettende Maßnahmen erlernen. In praxisnahen Übungen lernen sie, in Notfallsituationen richtig zu reagieren und Verletzten bis zum Eintreffen professioneller Hilfe beizustehen.",
    "programs.bureautique.title": "Bureautique",
    "programs.bureautique.desc": "Die Ausbildung Bureautique vermittelt den Teilnehmern grundlegende Fähigkeiten im Umgang mit Bürosoftware und Büroorganisation. Sie lernen, gängige Programme wie Microsoft Office (Word, Excel, PowerPoint, Outlook) effizient zu nutzen und erwerben organisatorische Kompetenzen, um Büroaufgaben effektiv bewältigen zu können.",
    "programs.physiotherapie.title": "Physiotherapeut/in",
    "programs.physiotherapie.desc": "Ausbildung in Physiotherapie und Rehabilitation. Die Studierenden erlernen Techniken der Krankengymnastik, Massagetherapie und Bewegungslehre, um Patienten bei der Wiederherstellung ihrer Mobilität und Schmerzlinderung zu helfen.",
    "programs.laboratoire.title": "Medizinisch-technische/r Laborassistent/in",
    "programs.laboratoire.desc": "Fokus auf Laboranalysen und Diagnostik. Die Ausbildung vermittelt Kenntnisse in Labortechnik, Probenentnahme, Analyseverfahren und Qualitätskontrolle, sodass Absolventen in medizinischen Laboratorien Tests und Auswertungen nach internationalen Standards durchführen können.",
    "programs.secretaire.title": "Medizinische/r Sekretär/in",
    "programs.secretaire.desc": "Ausbildung im Bereich medizinische Verwaltung und Dokumentation. Inhalte sind medizinische Terminologie, Patientenverwaltung, Abrechnungswesen sowie organisatorische Abläufe in Kliniken und Arztpraxen.",

    "diplomas.title": "Diplome",
    "diplomas.description": "Nach erfolgreichem Abschluss eines Programms erhalten die Absolventen ein staatlich anerkanntes Diplom in ihrem jeweiligen Fachgebiet. Unsere Diplome sind vom marokkanischen Bildungsministerium akkreditiert und landesweit gültig. Die offizielle Autorisierung unseres Instituts (Nr. 5/0/2025) garantiert, dass unser Abschluss den nationalen Ausbildungsstandards entspricht und von Behörden sowie Arbeitgebern in Marokko voll anerkannt wird.",
    "diplomas.description2": "Darüber hinaus legen wir großen Wert darauf, dass unsere Ausbildung international kompatibel ist. Unser Lehrplan orientiert sich an den Richtlinien renommierter internationaler Organisationen – beispielsweise den Ausbildungsrichtlinien der Weltgesundheitsorganisation (WHO) für Gesundheitsberufe und den UNESCO-Standards für technische und berufliche Bildung (TVET).",

    "languages.title": "Sprachkurse",
    "languages.description": "Sprachkenntnisse öffnen Türen – insbesondere im Gesundheitsbereich, der immer internationaler wird. Daher bietet das IPFPSP ergänzende Sprachkurse an, um unsere Schüler auf den globalen Arbeitsmarkt vorzubereiten.",
    "languages.german.title": "Deutschkurse",
    "languages.german.desc": "Im Hinblick auf die hohe Nachfrage nach Pflegekräften in Deutschland ermöglichen wir unseren Schülern Deutschunterricht bis zum Niveau B2. Unsere Deutschkurse orientieren sich am Gemeinsamen Europäischen Referenzrahmen für Sprachen (GER) und sind speziell auf medizinisches Fachpersonal zugeschnitten. Die Kursteilnehmer erwerben nicht nur allgemeine Sprachkenntnisse, sondern lernen auch berufsspezifische Terminologie (z. B. medizinische Fachausdrücke), um im deutschen Gesundheitssystem kommunizieren zu können.",
    "languages.german.levels": "Wir bieten Deutschkurse für alle Niveaustufen von A1 bis C1 an. Zusätzlich gibt es gezielte Vorbereitungskurse für anerkannte Prüfungen (Telc, ÖSD sowie Goethe-Zertifikate), um die Teilnehmer erfolgreich auf Sprachzertifikate vorzubereiten.",
    "languages.english.title": "Englischkurse",
    "languages.english.desc": "Englisch ist die internationale Verkehrssprache – auch im medizinischen Sektor. Wir bieten Englischunterricht an, der den Schülern hilft, medizinische Fachliteratur zu verstehen, mit ausländischen Kollegen zu kommunizieren und sich auf internationale Prüfungen vorzubereiten. Die Englischkurse decken allgemeine und fachbezogene Themen ab und orientieren sich ebenfalls am CEFR-Standard.",
    "languages.english.levels": "Wir bieten Englischkurse auf den Niveaustufen A1 bis C1 an. Zusätzlich bereiten unsere Vorbereitungskurse gezielt auf international anerkannte Englischprüfungen wie TOEFL und IELTS vor, damit die Teilnehmer erfolgreich ihre Sprachzertifikate erwerben können.",
    "languages.french.title": "Französischkurse",
    "languages.french.desc": "Als Bildungsinstitut in Marokko findet ein Großteil unseres Fachunterrichts auf Französisch statt. Für internationale Studierende oder jene, die ihre Französischkenntnisse vertiefen möchten, bieten wir zusätzliche Französischkurse an. Dies stellt sicher, dass alle unsere Schüler dem Unterricht folgen können und im Berufsleben in Marokko souverän auf Französisch kommunizieren.",
    "languages.french.levels": "Wir bieten Französischkurse auf den Niveaustufen A1 bis C1 an. Bei Bedarf bereiten wir die Teilnehmer auch auf offizielle Sprachprüfungen wie das DELF/DALF vor, um anerkannte Zertifikate in französischer Sprache zu erlangen.",

    "online.title": "Online Learning",
    "online.description": "Als modernes Institut nutzen wir die Möglichkeiten des Online-Lernens, um Bildung flexibler und zugänglicher zu gestalten. Unsere Schüler können auf einer digitalen Lernplattform auf Unterrichtsmaterialien zugreifen, Aufgaben einreichen und mit Dozenten sowie Mitschülern kommunizieren. Dieses blended learning-Modell (Mischung aus Präsenzunterricht und E-Learning) ermöglicht es den Studierenden, auch außerhalb des Campus und außerhalb der regulären Unterrichtszeiten zu lernen und zu üben.",
    "online.description2": "Bestimmte theoretische Kurse bieten wir teilweise oder ganz online an, was insbesondere für berufstätige Lernende oder Studierende aus anderen Städten von Vorteil ist. Live-Webinare, aufgezeichnete Vorlesungen und interaktive Online-Übungen ergänzen den Unterricht vor Ort. Dabei stellen wir sicher, dass die Online-Inhalte genauso qualitativ hochwertig sind wie der Präsenzunterricht.",
    "online.allCourses": "Alle unsere Kurse bieten wir auch online an, sodass Sie flexibel von zu Hause oder jedem anderen Ort aus lernen können. Wir setzen moderne E-Learning-Plattformen und digitale Unterrichtsmaterialien ein, um ein effektives und interaktives Lernerlebnis zu gewährleisten.",

    "companies.title": "Firmenangebote",
    "companies.description": "Neben der Ausbildung von Schülern arbeitet das IPFPSP auch mit Unternehmen, Gesundheitseinrichtungen und Organisationen zusammen. Unsere Firmenangebote richten sich an Krankenhäuser, Kliniken, Pflegeheime sowie Unternehmen und NGOs im Gesundheitssektor.",
    "companies.training.title": "Weiterbildungen & Inhouse-Schulungen",
    "companies.training.desc": "Wir konzipieren maßgeschneiderte Fortbildungen für das Personal von Gesundheitseinrichtungen. Beispielsweise bieten wir Erste-Hilfe-Kurse für Firmenmitarbeiter an, Schulungen in Krankenhausmanagement für Verwaltungsteams oder Auffrischungskurse in Pflegetechniken für Pflegekräfte.",
    "companies.partnerships.title": "Praktikums- und Ausbildungskooperationen",
    "companies.partnerships.desc": "Gesundheitsorganisationen können Partnerschaften mit uns eingehen, um Praktikumsplätze für unsere Schüler bereitzustellen. Durch solche Kooperationen profitieren beide Seiten: Die Schüler erhalten wertvolle Praxiserfahrung, und die Partner erhalten frühzeitig Einblick in den Nachwuchs und können potenzielle künftige Mitarbeiter kennenlernen.",
    "companies.recruitment.title": "Vermittlung von Fachkräften (Recruiting)",
    "companies.recruitment.desc": "Als Teil unseres Engagements fungieren wir als Vermittler zwischen unseren Absolventen und Arbeitgebern. Insbesondere für internationale Arbeitgeber bieten wir Unterstützung an: Wir bereiten unsere Schüler nicht nur sprachlich und fachlich auf den Auslandsjob vor, sondern stellen auch Kontakte zu Kliniken und Pflegeeinrichtungen (z. B. in Deutschland) her, die Fachkräfte suchen.",
    "companies.description2": "Für Unternehmen bieten wir maßgeschneiderte Schulungen und Kooperationen an. Wir organisieren zum Beispiel interne Firmenkurse, kooperieren mit Pflegeheimen und Kliniken, und stellen spezielle Arbeitgeberservices bereit, um Betriebe – besonders im Pflege- und Gesundheitssektor – bei der Personalentwicklung zu unterstützen.",

    "registration.title": "Anmeldung",
    "registration.step1.title": "Bewerbung einreichen",
    "registration.step1.desc": "Interessenten füllen zunächst das Anmeldeformular aus – entweder online über unsere Website oder persönlich vor Ort am Institut. Dabei sind Unterlagen wie ein Anschreiben/Motivationsschreiben, Lebenslauf, Kopien der letzten Schulzeugnisse bzw. des Diploms (z. B. Baccalauréat) sowie ein Ausweisdokument vorzulegen.",
    "registration.step2.title": "Prüfung der Voraussetzungen",
    "registration.step2.desc": "Unsere Aufnahmekommission prüft jede Bewerbung individuell. Je nach gewähltem Ausbildungsprogramm gibt es bestimmte Zugangsvoraussetzungen. Für die dreijährigen Diplomprogramme ist in der Regel das Abitur (Baccalauréat) oder ein gleichwertiger Schulabschluss erforderlich. Einige kürzere Ausbildungen sind bereits mit dem Abschluss der Mittelschule (9. Klasse) zugänglich.",
    "registration.step3.title": "Aufnahmeverfahren",
    "registration.step3.desc": "Wenn die formalen Kriterien erfüllt sind, laden wir die Bewerber zu einem Aufnahmeverfahren ein. Dies kann je nach Programm ein schriftlicher Eignungstest, ein persönliches Vorstellungsgespräch oder eine Kombination aus beidem sein. In diesem Schritt möchten wir die Motivation, die Grundkenntnisse (z. B. in Naturwissenschaften) und die sozialen Kompetenzen der Kandidaten kennenlernen.",
    "registration.step4.title": "Zulassung & Einschreibung",
    "registration.step4.desc": "Bewerber, die das Aufnahmeverfahren erfolgreich durchlaufen, erhalten einen Zulassungsbescheid. Anschließend beginnt die eigentliche Einschreibung: Die zukünftigen Schüler bestätigen ihren Platz, indem sie die Einschreibegebühren entrichten und die erforderlichen Formulare (Einschreibungsvertrag, interne Schulordnung etc.) unterzeichnen.",

    "faq.title": "FAQ (Häufige Fragen)",
    "faq.q1.question": "Welche Voraussetzungen gibt es für eine Bewerbung?",
    "faq.q1.answer": "Grundsätzlich benötigen Sie je nach gewähltem Programm einen bestimmten schulischen Abschluss. Die dreijährigen Diplomprogramme (z. B. diplomierte/r Krankenpfleger/in, Physiotherapeut/in) setzen in der Regel das marokkanische Baccalauréat (Abitur) oder einen gleichwertigen Schulabschluss voraus. Kürzere Qualifikationslehrgänge (z. B. Pflegeassistenz) sind teilweise schon mit einem mittleren Schulabschluss (Abschluss der 9. Klasse) zugänglich.",
    "faq.q2.question": "Wie lange dauern die Ausbildungen?",
    "faq.q2.answer": "Die Dauer der Ausbildung hängt vom jeweiligen Programm ab. Unsere angebotenen Ausbildungsgänge dauern im Regelfall zwischen einem und drei Jahren. Beispielsweise erstreckt sich die Ausbildung zur Pflegefachkraft über 3 Jahre, während ein Kurs zur Pflegeassistenz in 1 bis 2 Jahren abgeschlossen werden kann.",
    "faq.q3.question": "Ist das Diplom staatlich anerkannt?",
    "faq.q3.answer": "Ja, alle Abschlüsse des IPFPSP sind voll staatlich anerkannt. Unser Institut ist vom marokkanischen Staat genehmigt (Autorisierungsnummer 5/0/2025), und die von uns verliehenen Diplome sind national gültig. Absolventen können sich mit ihrem Abschluss in ganz Marokko bei öffentlichen wie privaten Gesundheitseinrichtungen bewerben.",
    "faq.q4.question": "Gibt es Praktika und unterstützt das Institut bei der Jobsuche?",
    "faq.q4.answer": "Ja, Praxisorientierung ist ein Kernbestandteil unserer Ausbildung. Alle Programme beinhalten verpflichtende Praktika, und wir kooperieren hierzu mit Krankenhäusern, Kliniken, Laboratorien und anderen Einrichtungen im Gesundheitssektor. Während der Praktika werden die Studierenden von erfahrenen Fachkräften angeleitet und sammeln wertvolle Berufserfahrung.",
    "faq.q5.question": "Werden Sprachkurse angeboten, insbesondere für Deutschland?",
    "faq.q5.answer": "Ja, wir bieten begleitend zur Fachausbildung auch Sprachkurse an (siehe Abschnitt Sprachkurse oben). Besonders gefragt sind unsere Deutschkurse, die bis zum Niveau B2 des GER führen. Sie richten sich vor allem an Schüler, die überlegen, nach dem Abschluss in Deutschland zu arbeiten oder weiterzulernen.",
    "faq.q6.question": "Wann beginnt das Schuljahr und wie läuft die Einschreibung?",
    "faq.q6.answer": "Das Ausbildungsjahr am IPFPSP beginnt in der Regel im September. Viele unserer Kurse starten zum Herbst, parallel zum offiziellen marokkanischen Schuljahr. Die Bewerbungsphase öffnet meist bereits im Frühjahr oder Frühsommer desselben Jahres. Wir empfehlen, sich so früh wie möglich zu bewerben, da die Plätze begrenzt sind.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const saved = localStorage.getItem("language") as Language | null
    if (saved && (saved === "ar" || saved === "fr" || saved === "de")) {
      setLanguageState(saved)
      document.documentElement.dir = saved === "ar" ? "rtl" : "ltr"
    } else {
      document.documentElement.dir = "rtl"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const dir = language === "ar" ? "rtl" : "ltr"

  const t = (key: string): string => {
    const translationDict = translations[language as keyof typeof translations]
    return (translationDict as any)[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
